/**:
   ros__parameters:
     queue_size: 2 #num of threads
     tolerance: 0.01 # referring to temporal tolerance
     target_frame: "base_link" # transform and publish output on this frame
     use_inf: false  #If disabled, report infinite range (no obstacle) as range_max + 1. Otherwise report infinite range as +inf.
