# Tire specs 125 / 80 R13 Front
# S.I. measurements
/**:
  ros__parameters:
    wheel_radius: 0.2651 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.125 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.687 # between front wheel center and rear wheel center
    wheel_tread: 1.112   # between left wheel center and right wheel center
    front_overhang: 0.313 # between front wheel center and vehicle front
    rear_overhang: 0.339 # between rear wheel center and vehicle rear
    left_overhang: 0.25 # between left wheel center and vehicle left
    right_overhang: 0.25 # between right wheel center and vehicle right
    vehicle_height: 1.461
    max_steer_angle: 0.57575 # was 0.4606 before
