video_tools:
  video_source: "camera" # Choices: rosbag2, camera
  rosbag2_path: ""
  rosbag2_topics: "/zed/zed_node/rgb_raw/camera_info /zed/zed_node/rgb_raw/image_raw_color /zed/zed_node/depth/camera_info /zed/zed_node/confidence/confidence_map /tf /tf_static /zed/zed_node/depth/depth_registered"
  svo_path: ""  

object_detection_launch:
  enable_3d_object_detection: "True"
  rviz: "False"

  model: "extending_yolov8m"
  tracker: "bytetrack.yaml"
  device: "cuda:0"
  enable: "True"
  threshold: "0.5"
  image_reliability: "1" # Choices: 0=system default, 1=Reliable, 2=Best Effort
  depth_image_reliability: "1" # Choices: 0=system default, 1=Reliable, 2=Best Effort
  depth_info_reliability: "1" # Choices: 0=system default, 1=Reliable, 2=Best Effort
  depth_image_units_divisor: "1"
  maximum_detection_threshold: "0.3"

  input_image_topic: "/zed/zed_node/rgb_raw/image_raw_color"
  input_depth_info_topic: "/zed/zed_node/depth/camera_info"
  input_depth_topic: "/zed/zed_node/depth/depth_registered"
  target_frame: "base_link"