<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rt_map_launch</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="g.gkovopoulos@greendino.nl">georgios</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>autoware_map_tf_generator</depend>
  <depend>autoware_map_loader</depend>
  <depend>autoware_lanelet2_map_visualizer</depend>
  <depend>autoware_map_projection_loader</depend>
  <depend>autoware_global_parameter_loader</depend>
  <depend>rviz2</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
