<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rt_localization_launcher</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="g.gkovopoulos@greendino.nl">twizy</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>earth_to_map_transform</depend>
  <depend>ecef_to_geopose_transformation</depend>
  <depend>gd_kinematic_state_publisher</depend>
  <depend>autoware_geo_pose_projector</depend>
  <depend>autoware_twist2accel</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
